#!/usr/bin/env python3
"""Compose the individual panel PNGs into single laid-out multi-panel figures.

Each row is packed to a common height with per-panel widths proportional to the
panel's aspect ratio (the standard journal layout), rows left-aligned, small gaps.
Panel letters (a/b/c) are overlaid here, so panel PNGs must not carry baked-in letters.

Inputs/outputs: manuscript/figures_v8/. Writes fig{1,2,3,4}_composite.png/.svg (the four
main-text figures) and figS2_inflation_exhibit.png/.svg (the two-panel supplementary
figure). Supplementary Figs. S1 and S3 are single-panel and are not composited.

This script only re-lays out panel PNGs that already exist, so it always runs. The Figure 4
panels are regenerated by phase1/repositioning_model_reverse.py (all inputs present).
"""
from __future__ import annotations
from pathlib import Path
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

FIG = Path(__file__).resolve().parent.parent.parent / "manuscript/figures_v8"


LETTERS = "abcdefgh"


def compose(rows, out_stem, row_h=3.0, gap=0.10, pad=0.05, letters=True,
            row_heights=None, panel_scales=None):
    """rows: list[list[str]] of panel filenames (relative to FIG).

    Overlays a bold panel letter (a, b, c, … in row-major order) at the top-left
    of each panel so lettering is uniform across figures. Panels must NOT carry
    baked-in letters.

    row_heights: optional list giving each row its own height (inches). Lets a
    wide schematic row (e.g. Fig 1's architecture panel) render taller, and therefore
    more legibly, than the data-panel row below it. Defaults to uniform row_h.

    panel_scales: optional list-of-lists (mirroring `rows`) of per-panel height
    multipliers. Panels are scaled to a common ROW HEIGHT, so a panel authored on a
    TALLER figure is shrunk harder and its baked-in type comes out smaller than its
    neighbour's. Scaling a panel's height by its authored height equalises the shrink
    factor, matching apparent font size across a row WITHOUT regenerating the panels.
    Panels are top-aligned within the row. Defaults to 1.0 everywhere.
    """
    # Every panel gets a left gutter (LM) and its letter is drawn INSIDE that gutter, so a
    # letter can never sit on top of the panel's y-axis label. The first panel of a row puts
    # its gutter at the figure's left margin, so the leading letters (a, and the letter of
    # each row below it) line up flush at the figure edge rather than being carried inward by
    # the row centring — a narrow panel over a wide one (Fig. 1's funnel above the
    # architecture panel) would otherwise read as indented.
    LM = 0.30 if letters else 0.0            # per-panel left gutter holding the letter
    rhs = row_heights if row_heights is not None else [row_h] * len(rows)
    scs = panel_scales if panel_scales is not None else [[1.0] * len(r) for r in rows]
    imgs = [[mpimg.imread(FIG / p) for p in r] for r in rows]
    ars = [[im.shape[1] / im.shape[0] for im in r] for r in imgs]
    # per-panel height (row height x its scale) and the width its aspect ratio implies
    hs = [[rh * s for s in sc] for sc, rh in zip(scs, rhs)]
    ws = [[a * h for a, h in zip(ar, hr)] for ar, hr in zip(ars, hs)]
    row_widths = [sum(w + LM for w in wr) + gap * (len(wr) - 1) for wr in ws]
    row_tops = [max(hr) for hr in hs]        # a scaled-up panel sets its row's height
    canvas_w = max(row_widths)
    fig_w = canvas_w + 2 * pad
    fig_h = sum(row_tops) + gap * (len(rows) - 1) + 2 * pad
    fig = plt.figure(figsize=(fig_w, fig_h))
    y = fig_h - pad
    k = 0
    for row, wr, hr, rw, rt in zip(imgs, ws, hs, row_widths, row_tops):
        y -= rt
        x = pad          # rows are LEFT-aligned so every row's leading letter shares the
                         # same left margin; centring would carry a narrow row's letter in
        for im, w, h in zip(row, wr, hr):
            py = y + rt - h                              # top-align within the row
            axx = fig.add_axes([(x + LM) / fig_w, py / fig_h, w / fig_w, h / fig_h])
            axx.imshow(im)
            axx.axis("off")
            if letters:                                  # letter sits in the panel's gutter
                fig.text(x / fig_w, (y + rt - 0.02) / fig_h,
                         LETTERS[k], fontsize=15, fontweight="bold",
                         ha="left", va="top")
            k += 1
            x += w + LM + gap
        y -= gap
    for ext in ("png", "svg"):
        fig.savefig(FIG / f"{out_stem}.{ext}", dpi=200)
    plt.close(fig)
    print(f"wrote {out_stem} ({fig_w:.1f}x{fig_h:.1f} in)")


def main():
    # Panel order within each figure follows first mention in the Results text.
    # Figure 1: a selection funnel; b architecture (full-width overview). The text
    # introduces the cohort before the feature modules.
    # The per-module standalone-AUC panel was relocated to Supplementary Fig. S1 (Jul 2026):
    # it conflicted conceptually with the Fig. 2c decomposition and the headline AUC.
    # figS1_module_auc.png is now built as a standalone supplementary figure.
    compose([["fig1a_funnel.png"],
             ["fig1b_architecture.png"]],
            "fig1_composite", row_heights=[3.5, 4.2])
    # Figure 2 (trial-level only; arm-level moved to Supplementary): a ROC trial,
    # b per-fold AUC distributions, c signal decomposition. Panel order follows the text,
    # which reports the headline AUC and its fold spread before asking which input does the work.
    compose([["fig2a_roc_trial.png", "fig2b_fold_distributions.png", "fig2c_decomposition.png"]],
            "fig2_composite")
    # Figure 3 (mechanism instrument): a case features + b pathway-overlap-by-outcome.
    # The drug-class PCA panel was cut (Jul 2026): classes did not separate in PC
    # space beyond a label-shuffled null (silhouette -0.286 vs -0.285, p=0.56), so
    # "drug classes occupy distinct regions" was unsupported. Panels: make_fig3_v8.py.
    compose([["fig3a_case_features.png", "fig3b_pathway_by_outcome.png"]],
            "fig3_composite")
    # Figure 4 (rescue / repositioning): a indication-selection three-test bar (the
    # "First" analysis in the text) + b repoDB recovery scatter (the "Second").
    # Panels generated by repositioning_model_reverse.py.
    # The panels are authored at different figure heights (a 4.0in, b 5.2in), so at a common
    # row height b would be shrunk 1.3x harder than a and its type would read smaller.
    # Scaling b's height by 5.2/4.0 equalises the shrink, matching apparent font size.
    compose([["fig4a_indication_selection.png", "fig4b_rescue.png"]],
            "fig4_composite", panel_scales=[[1.0, 5.2 / 4.0]])
    # Supplementary Fig. S2 (evaluation inflation): a TrialBench drug-approval benchmark
    # + b Phase III trials. Panels generated by benchmark/make_inflation_exhibit.py.
    # Lettered here so the supplementary figure matches the main-figure format.
    # Supplementary Figs. S1 and S3 are single-panel and need no composite.
    compose([["figS2a_trialbench.png", "figS2b_phase3.png"]],
            "figS2_inflation_exhibit")


if __name__ == "__main__":
    main()
